[theme]
primaryColor = "#588157"
backgroundColor = "#121910"
secondaryBackgroundColor = "#182215"
textColor = "#e5ede0"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
